const fs = require("fs/promises");
const path = require("path");
const esbuild = require("esbuild");
const { createManifest } = require("../src/extension/manifests/create-manifest.js");

const projectRoot = path.resolve(__dirname, "..");
const outputDir = path.join(projectRoot, "dist");
const watchMode = process.argv.includes("--watch");
const contentCssPath = path.join(
  projectRoot,
  "src",
  "extension",
  "styles",
  "content.css",
);

const banner = [
  "// Generated by esbuild via scripts/build.js. Do not edit this file directly.",
].join("\n");

const browserTargets = [
  {
    name: "chrome",
    esbuildTarget: ["chrome109"],
  },
  {
    name: "firefox",
    esbuildTarget: ["firefox109"],
  },
];

function getOutdir(browser) {
  return path.join(outputDir, browser.name);
}

async function writeExtensionAssets(browser) {
  const browserOutputDir = getOutdir(browser);
  await fs.mkdir(browserOutputDir, { recursive: true });
  await fs.copyFile(contentCssPath, path.join(browserOutputDir, "content.css"));
  await fs.writeFile(
    path.join(browserOutputDir, "manifest.json"),
    `${JSON.stringify(createManifest(browser.name), null, 2)}\n`,
    "utf8",
  );
}

function createWriteAssetsPlugin(browser) {
  return {
    name: `write-extension-assets-${browser.name}`,
    setup(build) {
      build.onEnd(async (result) => {
        if (result.errors.length > 0) {
          return;
        }

        await writeExtensionAssets(browser);
      });
    },
  };
}

function createBuildOptions(browser) {
  return {
    entryPoints: {
      "content-script": path.join(
        projectRoot,
        "src",
        "extension",
        "content-script",
        "main.js",
      ),
      background: path.join(
        projectRoot,
        "src",
        "extension",
        "background",
        "main.js",
      ),
    },
    outdir: getOutdir(browser),
    entryNames: "[name]",
    bundle: true,
    format: "iife",
    platform: "browser",
    target: browser.esbuildTarget,
    banner: { js: banner },
    charset: "utf8",
    logLevel: "info",
    plugins: [createWriteAssetsPlugin(browser)],
  };
}

async function run() {
  await fs.rm(outputDir, { recursive: true, force: true });

  if (watchMode) {
    const contexts = await Promise.all(
      browserTargets.map((browser) => esbuild.context(createBuildOptions(browser))),
    );

    await Promise.all(contexts.map((context) => context.watch()));
    console.log("Watching extension builds for Chrome and Firefox...");
    return;
  }

  await Promise.all(
    browserTargets.map((browser) => esbuild.build(createBuildOptions(browser))),
  );
}

run().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
