const path = require("path");
const esbuild = require("esbuild");

const projectRoot = path.resolve(__dirname, "..");
const outputDir = path.join(projectRoot, "dist");
const watchMode = process.argv.includes("--watch");

const banner = [
  "// Generated by esbuild via scripts/build.js. Do not edit this file directly.",
].join("\n");

const buildOptions = {
  entryPoints: {
    main: path.join(projectRoot, "src", "main.js"),
    "otag-dropdown": path.join(projectRoot, "src", "otag-dropdown", "main.js"),
    "card-page-tags": path.join(projectRoot, "src", "card-page-tags", "main.js"),
  },
  outdir: outputDir,
  entryNames: "[name]",
  bundle: true,
  format: "iife",
  platform: "browser",
  target: ["chrome109", "firefox109", "safari16"],
  banner: { js: banner },
  charset: "utf8",
  logLevel: "info",
};

async function run() {
  if (watchMode) {
    const context = await esbuild.context(buildOptions);
    await context.watch();
    console.log("Watching for changes...");
    return;
  }

  await esbuild.build(buildOptions);
}

run().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
